# Generated by Django 6.0 on 2025-12-12 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "isbn",
                    models.CharField(
                        help_text="ISBN-10 or ISBN-13",
                        max_length=13,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("page_count", models.PositiveIntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "books",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["isbn"], name="books_isbn_ce4a1a_idx"),
                    models.Index(fields=["is_available"], name="books_is_avai_91a3e1_idx"),
                    models.Index(fields=["title", "author"], name="books_title_e8b1ad_idx"),
                ],
            },
        ),
    ]
