# Generated by Django 6.0 on 2025-12-12 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["user", "returned_at"], name="loans_user_id_c50bf4_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["book", "returned_at"], name="loans_book_id_ea0a0e_idx"),
        ),
    ]
